Handle case where url is FetchRequest
adobe/node-fetch-retry pull request #29
Opened 2020-10-13 12:04 UTC by joachimroeleveld

## Description

This PR handles the case where `url` is an instance of `FetchRequest` which is supported by `node-fetch`. Currently, the following is logged in case of a timeout: `network timeout at [object Request]`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-10-13 22:48 UTC, tmathern commented
Thank you for your contribution.
Is this PR ready for review?

2020-10-15 18:04 UTC, jdelbick requested changes
Thanks for your contribution. Could you please add a test case covering this? Otherwise, it looks good.

2020-10-15 18:04 UTC, jdelbick commented on index.js
> +                        return reject(new FetchError(`network timeout at ${typeof url === 'string' ? url : url.url}`, 'request-timeout'));
could you add a test case covering the error containing a FetchRequest?

2020-10-16 09:05 UTC, joachimroeleveld commented
Unfortunately I don't have time to pick this up soon.

2020-10-16 09:05 UTC, closed without merging